-- -- ==============================================================================
-- -- ⚠️ تحذير: هذا القسم يقوم بحذف الجداول القديمة لإعادة بنائها ⚠️
-- -- ==============================================================================

-- -- بنمسح الـ Views الأول عشان بتعتمد على الجداول
-- DROP VIEW IF EXISTS posts_view;
-- DROP VIEW IF EXISTS comments_full_view;

-- -- بنمسح الجداول الفرعية
-- DROP TABLE IF EXISTS comment_votes;
-- DROP TABLE IF EXISTS comments;
-- DROP TABLE IF EXISTS post_votes;
-- DROP TABLE IF EXISTS follows;
-- DROP TABLE IF EXISTS posts;

-- -- ⚠️ لو عايز تمسح البروفايلات واليوزرز القدام ابدأ من جديد، شيل الشرطتين (--) من السطر الجاي
-- -- DROP TABLE IF EXISTS profiles; 


-- -- ==============================================================================
-- -- 1. جدول البروفايلات (Profiles)
-- -- (لو الجدول موجود مش هيعمل حاجة، لو مسحته فوق هيتكريت من جديد)
-- -- ==============================================================================
-- create table if not exists public.profiles (
--   id uuid references auth.users on delete cascade not null primary key,
--   email varchar(255) unique not null,
--   name varchar(255),
--   avatar_url varchar(255),
--   created_at timestamp with time zone default timezone('utc'::text, now()) not null,
--   updated_at timestamp with time zone default timezone('utc'::text, now()) not null
-- );

-- -- ==============================================================================
-- -- 2. جدول المتابعة (Follows)
-- -- ==============================================================================
-- create table public.follows (
--   follower_id uuid references public.profiles(id) on delete cascade not null,
--   following_id uuid references public.profiles(id) on delete cascade not null,
--   created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
--   primary key (follower_id, following_id),
--   constraint cant_follow_self check (follower_id != following_id)
-- );

-- -- ==============================================================================
-- -- 3. جدول البوستات (Posts)
-- -- ==============================================================================
-- create table public.posts (
--   id bigint generated by default as identity primary key,
--   user_id uuid references public.profiles(id) on delete cascade not null,
--   content text,
--   image_url text,
--   created_at timestamp with time zone default timezone('utc'::text, now()) not null
-- );

-- -- ==============================================================================
-- -- 4. جدول لايكات البوستات (Post Votes)
-- -- ==============================================================================
-- create table public.post_votes (
--   user_id uuid references public.profiles(id) on delete cascade not null,
--   post_id bigint references public.posts(id) on delete cascade not null,
--   vote_type int not null check (vote_type in (1, -1)), -- 1 like, -1 dislike
--   created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
--   primary key (user_id, post_id)
-- );

-- -- ==============================================================================
-- -- 5. جدول التعليقات (Comments) - يدعم الردود (Sub-comments)
-- -- ==============================================================================
-- create table public.comments (
--   id bigint generated by default as identity primary key,
--   user_id uuid references public.profiles(id) on delete cascade not null,
--   post_id bigint references public.posts(id) on delete cascade not null,
--   parent_id bigint references public.comments(id) on delete cascade, -- للردود
--   content text not null,
--   created_at timestamp with time zone default timezone('utc'::text, now()) not null
-- );

-- -- ==============================================================================
-- -- 6. جدول لايكات التعليقات (Comment Votes)
-- -- ==============================================================================
-- create table public.comment_votes (
--   user_id uuid references public.profiles(id) on delete cascade not null,
--   comment_id bigint references public.comments(id) on delete cascade not null,
--   vote_type int not null check (vote_type in (1, -1)),
--   created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
--   primary key (user_id, comment_id)
-- );


-- -- ==============================================================================
-- -- 7. الـ Views (الجداول المجمعة للعرض في التطبيق)
-- -- ==============================================================================

-- -- A. Posts View (للصفحة الرئيسية)
-- create or replace view posts_view as
-- select 
--   p.id,
--   p.user_id,
--   p.content,
--   p.image_url,
--   p.created_at,
--   pr.name as user_name,
--   pr.avatar_url as user_avatar,
--   (select count(*) from public.post_votes v where v.post_id = p.id and v.vote_type = 1) as likes_count,
--   (select count(*) from public.post_votes v where v.post_id = p.id and v.vote_type = -1) as dislikes_count,
--   (select count(*) from public.comments c where c.post_id = p.id) as comments_count
-- from public.posts p
-- left join public.profiles pr on p.user_id = pr.id;

-- -- B. Comments View (لصفحة التفاصيل - بيجيب التعليقات والردود واللايكات بتاعتهم)
-- create or replace view comments_full_view as
-- select 
--   c.id,
--   c.post_id,
--   c.parent_id,
--   c.content,
--   c.created_at,
--   c.user_id,
--   pr.name as user_name,
--   pr.avatar_url as user_avatar,
--   (select count(*) from public.comment_votes cv where cv.comment_id = c.id and cv.vote_type = 1) as likes_count,
--   (select count(*) from public.comment_votes cv where cv.comment_id = c.id and cv.vote_type = -1) as dislikes_count
-- from public.comments c
-- left join public.profiles pr on c.user_id = pr.id
-- order by c.created_at asc;


-- -- ==============================================================================
-- -- 8. سياسات الحماية (RLS Security Policies)
-- -- ==============================================================================

-- -- تفعيل RLS لكل الجداول
-- alter table public.profiles enable row level security;
-- alter table public.posts enable row level security;
-- alter table public.comments enable row level security;
-- alter table public.follows enable row level security;
-- alter table public.post_votes enable row level security;
-- alter table public.comment_votes enable row level security;

-- -- (Policies) سياسات بسيطة تسمح بالقراءة للكل والكتابة لصاحب الحساب فقط

-- -- Profiles
-- create policy "Public profiles are viewable by everyone" on profiles for select using (true);
-- create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- -- Posts
-- create policy "Public posts are viewable by everyone" on posts for select using (true);
-- create policy "Users can insert own posts" on posts for insert with check (auth.uid() = user_id);
-- create policy "Users can delete own posts" on posts for delete using (auth.uid() = user_id);

-- -- Comments
-- create policy "Public comments are viewable by everyone" on comments for select using (true);
-- create policy "Users can insert own comments" on comments for insert with check (auth.uid() = user_id);
-- create policy "Users can delete own comments" on comments for delete using (auth.uid() = user_id);

-- -- Votes (Post & Comment)
-- create policy "Public votes are viewable by everyone" on post_votes for select using (true);
-- create policy "Users can vote" on post_votes for insert with check (auth.uid() = user_id);
-- create policy "Users can unvote" on post_votes for delete using (auth.uid() = user_id);

-- create policy "Public comment votes are viewable by everyone" on comment_votes for select using (true);
-- create policy "Users can vote on comments" on comment_votes for insert with check (auth.uid() = user_id);
-- create policy "Users can unvote on comments" on comment_votes for delete using (auth.uid() = user_id);

-- -- Follows
-- create policy "Public follows are viewable by everyone" on follows for select using (true);
-- create policy "Users can follow" on follows for insert with check (auth.uid() = follower_id);
-- create policy "Users can unfollow" on follows for delete using (auth.uid() = follower_id);


-- -- ==============================================================================
-- -- 9. (اختياري) تريجر لإنشاء البروفايل تلقائياً عند التسجيل
-- -- ==============================================================================
-- create or replace function public.handle_new_user() 
-- returns trigger as $$
-- begin
--   insert into public.profiles (id, email, name)
--   values (new.id, new.email, new.raw_user_meta_data->>'name');
--   return new;
-- end;
-- $$ language plpgsql security definer;

-- -- بنمسح التريجر القديم لو موجود عشان منعاً للتكرار
-- drop trigger if exists on_auth_user_created on auth.users;

-- create trigger on_auth_user_created
--   after insert on auth.users
--   for each row execute procedure public.handle_new_user();



this another version for create many things 


now we create new one 


-- ==============================================================================
-- ⚠️ تنظيف القديم (حذف الجداول والـ Views لإعادة بنائها)
-- ==============================================================================
DROP VIEW IF EXISTS posts_view;
DROP VIEW IF EXISTS comments_full_view;

DROP TABLE IF EXISTS bookmarks;
DROP TABLE IF EXISTS user_watchlist;
DROP TABLE IF EXISTS comment_votes;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS post_votes;
DROP TABLE IF EXISTS follows;
DROP TABLE IF EXISTS posts;

-- (تم الإبقاء على profiles عشان المستخدمين ميتمسحوش)
-- DROP TABLE IF EXISTS profiles; 


-- ==============================================================================
-- 1. جدول البروفايلات (Profiles)
-- ==============================================================================
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email varchar(255) unique not null,
  name varchar(255),
  avatar_url varchar(255),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==============================================================================
-- 2. جدول متابعة الأشخاص (Follows)
-- ==============================================================================
create table public.follows (
  follower_id uuid references public.profiles(id) on delete cascade not null,
  following_id uuid references public.profiles(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (follower_id, following_id),
  constraint cant_follow_self check (follower_id != following_id)
);

-- ==============================================================================
-- 3. جدول متابعة الأسهم (Watchlist)
-- ==============================================================================
create table public.user_watchlist (
  user_id uuid references public.profiles(id) on delete cascade not null,
  stock_symbol text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (user_id, stock_symbol)
);

-- ==============================================================================
-- 4. جدول البوستات (Posts)
-- ==============================================================================
create table public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  content text,
  image_url text,
  sentiment varchar(10) check (sentiment in ('bullish', 'bearish')), 
  cashtags text[], 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==============================================================================
-- 5. جدول لايكات البوستات (Post Votes)
-- ==============================================================================
create table public.post_votes (
  user_id uuid references public.profiles(id) on delete cascade not null,
  post_id bigint references public.posts(id) on delete cascade not null,
  vote_type int not null check (vote_type in (1, -1)),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (user_id, post_id)
);

-- ==============================================================================
-- 6. جدول حفظ البوستات (Bookmarks)
-- ==============================================================================
create table public.bookmarks (
  user_id uuid references public.profiles(id) on delete cascade not null,
  post_id bigint references public.posts(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (user_id, post_id)
);

-- ==============================================================================
-- 7. جدول التعليقات (Comments)
-- ==============================================================================
create table public.comments (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  post_id bigint references public.posts(id) on delete cascade not null,
  parent_id bigint references public.comments(id) on delete cascade,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==============================================================================
-- 8. جدول لايكات التعليقات (Comment Votes)
-- ==============================================================================
create table public.comment_votes (
  user_id uuid references public.profiles(id) on delete cascade not null,
  comment_id bigint references public.comments(id) on delete cascade not null,
  vote_type int not null check (vote_type in (1, -1)),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (user_id, comment_id)
);


-- ==============================================================================
-- 9. الـ Views (الجداول المجمعة)
-- ==============================================================================

-- A. Posts View
create or replace view posts_view as
select 
  p.id,
  p.user_id,
  p.content,
  p.image_url,
  p.created_at,
  p.sentiment,
  p.cashtags,
  pr.name as user_name,
  pr.avatar_url as user_avatar,
  (select count(*) from public.post_votes v where v.post_id = p.id and v.vote_type = 1) as likes_count,
  (select count(*) from public.post_votes v where v.post_id = p.id and v.vote_type = -1) as dislikes_count,
  (select count(*) from public.comments c where c.post_id = p.id) as comments_count
from public.posts p
left join public.profiles pr on p.user_id = pr.id;

-- B. Comments View
create or replace view comments_full_view as
select 
  c.id,
  c.post_id,
  c.parent_id,
  c.content,
  c.created_at,
  c.user_id,
  pr.name as user_name,
  pr.avatar_url as user_avatar,
  (select count(*) from public.comment_votes cv where cv.comment_id = c.id and cv.vote_type = 1) as likes_count,
  (select count(*) from public.comment_votes cv where cv.comment_id = c.id and cv.vote_type = -1) as dislikes_count
from public.comments c
left join public.profiles pr on c.user_id = pr.id
order by c.created_at asc;


-- ==============================================================================
-- 10. سياسات الحماية (RLS Security Policies)
-- 🔥 تم إضافة أوامر DROP POLICY لتجنب الأخطاء 🔥
-- ==============================================================================

-- تفعيل RLS
alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.follows enable row level security;
alter table public.post_votes enable row level security;
alter table public.comment_votes enable row level security;
alter table public.bookmarks enable row level security;
alter table public.user_watchlist enable row level security;

-- 1. Profiles (مسح القديم قبل إنشاء الجديد)
drop policy if exists "Public profiles viewable" on profiles;
drop policy if exists "Users update own" on profiles;

create policy "Public profiles viewable" on profiles for select using (true);
create policy "Users update own" on profiles for update using (auth.uid() = id);

-- 2. Posts
drop policy if exists "Public posts viewable" on posts;
drop policy if exists "Users insert own posts" on posts;
drop policy if exists "Users delete own posts" on posts;

create policy "Public posts viewable" on posts for select using (true);
create policy "Users insert own posts" on posts for insert with check (auth.uid() = user_id);
create policy "Users delete own posts" on posts for delete using (auth.uid() = user_id);

-- 3. Comments
drop policy if exists "Public comments viewable" on comments;
drop policy if exists "Users insert own comments" on comments;
drop policy if exists "Users delete own comments" on comments;

create policy "Public comments viewable" on comments for select using (true);
create policy "Users insert own comments" on comments for insert with check (auth.uid() = user_id);
create policy "Users delete own comments" on comments for delete using (auth.uid() = user_id);

-- 4. Votes
drop policy if exists "Public votes viewable" on post_votes;
drop policy if exists "Users vote posts" on post_votes;
drop policy if exists "Users unvote posts" on post_votes;

create policy "Public votes viewable" on post_votes for select using (true);
create policy "Users vote posts" on post_votes for insert with check (auth.uid() = user_id);
create policy "Users unvote posts" on post_votes for delete using (auth.uid() = user_id);

drop policy if exists "Public comment votes viewable" on comment_votes;
drop policy if exists "Users vote comments" on comment_votes;
drop policy if exists "Users unvote comments" on comment_votes;

create policy "Public comment votes viewable" on comment_votes for select using (true);
create policy "Users vote comments" on comment_votes for insert with check (auth.uid() = user_id);
create policy "Users unvote comments" on comment_votes for delete using (auth.uid() = user_id);

-- 5. Follows
drop policy if exists "Public follows viewable" on follows;
drop policy if exists "Users follow" on follows;
drop policy if exists "Users unfollow" on follows;

create policy "Public follows viewable" on follows for select using (true);
create policy "Users follow" on follows for insert with check (auth.uid() = follower_id);
create policy "Users unfollow" on follows for delete using (auth.uid() = follower_id);

-- 6. Bookmarks
drop policy if exists "Users view own bookmarks" on bookmarks;
drop policy if exists "Users bookmark posts" on bookmarks;
drop policy if exists "Users remove bookmark" on bookmarks;

create policy "Users view own bookmarks" on bookmarks for select using (auth.uid() = user_id);
create policy "Users bookmark posts" on bookmarks for insert with check (auth.uid() = user_id);
create policy "Users remove bookmark" on bookmarks for delete using (auth.uid() = user_id);

-- 7. Watchlist
drop policy if exists "Users view own watchlist" on user_watchlist;
drop policy if exists "Users add to watchlist" on user_watchlist;
drop policy if exists "Users remove from watchlist" on user_watchlist;

create policy "Users view own watchlist" on user_watchlist for select using (auth.uid() = user_id);
create policy "Users add to watchlist" on user_watchlist for insert with check (auth.uid() = user_id);
create policy "Users remove from watchlist" on user_watchlist for delete using (auth.uid() = user_id);


-- ==============================================================================
-- 11. تريجر إنشاء البروفايل (Trigger)
-- ==============================================================================
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, name)
  values (new.id, new.email, new.raw_user_meta_data->>'name');
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();