create table public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  content text,
  image_url text,
  sentiment varchar(10) check (sentiment in ('bullish', 'bearish')), 
  cashtags text[], 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);